### PR TITLE
WIP: Documentation Overhaul

### PR DESCRIPTION
**Pull request by kanav99**

### CODE REVIEW

**Comment by kanav99** [comment]
Needs JuliaDiffEq/DiffEqBase.jl#399
Comments: 
1. Should we shift to the new frontend of documenter?
2. I think we should update the DiffEqOperators docs. Need some help for it.
3. I have made an action which generates a temporary link hosting the PR's documentation. Do we need it?
4. Why does /apis/diffeqbase exist? Its basically empty

Check out new frontend here - https://sharp-nobel-730811.netlify.com/features/callback_functions/

**Comment by ChrisRackauckas** [comment]
>I have made an action which generates a temporary link hosting the PR's documentation. Do we need it?

Sounds great!

>Why does /apis/diffeqbase exist? Its basically empty

It was a bad idea.

>Should we shift to the new frontend of documenter?

Looks good, I like the nesting

**Comment by ChrisRackauckas** [comment]
>I think we should update the DiffEqOperators docs. Need some help for it.

Really dig in and ask questions. This will matter for the linear solver stuff and DAEs.

**Comment by kanav99** [comment]
The DiffEqBase and DiffEqProblemLibrary should be tagged before this can be merged.

**Comment by ChrisRackauckas** [comment]
Let's try to get some of this in since it's already a lot.

**Comment by kanav99** [comment]
Woops the secret could not be found. Is the spelling correct `NETLIFY_SECRET` @ChrisRackauckas ?

**Comment by ChrisRackauckas** [comment]
yes

**Comment by ChrisRackauckas** [comment]
We can keep working on that.

**Pull request merged**
