### PR TITLE
JumpProblem - MassActionJump updates

### PR DESCRIPTION
**Pull request by isaacsas**
1. Added note explaining how to create zeroth order reactions
2. Added note explaining that species indices within stoichiometry vectors should be ordered from smallest to largest index.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
>Added note explaining that species indices within stoichiometry vectors should be ordered from smallest to largest index.

Why is that true?

**Comment by isaacsas** [comment]
I don't think it would actually break anything, but I was thinking it could have performance implications. I also haven't tested whether passing species out of order could have any issues.

**Comment by ChrisRackauckas** [comment]
Oh yes, it would have performance implications given the indexing order. But the way it's written it sounds like something could break.

**Comment by isaacsas** [comment]
I could change it from "should" be ordered to "are recommended".

**Comment by isaacsas** [comment]
Ok, fixed the wording.

**Pull request merged**
