### PR TITLE
changed sparse(A) by A=sparse(A)

### PR DESCRIPTION
**Pull request by WouterJRV**
sparse!(A) does not seem to exist...

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Thanks!

**Comment by WouterJRV** [comment]
It's not completely the end of the story it seems, sparse to my particular problem still gives the error though I haven't succeeded so far in making the test problem fail as well.

**Comment by ChrisRackauckas** [comment]
Has this been tracked down?

**Comment by WouterJRV** [comment]
> Has this been tracked down?

It seems something subtle, I've been trying to give the test problem specified noise, complex contributions, zeros in A, time-adaptive methods and a number of different options without problems

For the problems with which there is this error, I see that the error "no method matching zeros(Type::any)" vanishes either if A is not sparse, or if I put reltol=Inf.

**Pull request merged**
