### PR TITLE
Some improvements to the Sobol sensitivity

### PR DESCRIPTION
**Pull request by Beramos**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@Vaibhavdixit02 this will need more changes with the new version?

**Comment by ChrisRackauckas** [comment]
Thanks, but this has been supersceded since the new updates to DiffEqSensitivity are coming with a major docs overhaul here!

**Comment by Vaibhavdixit02** [comment]
Don't know how I missed this. Sorry to keep you waiting @Beramos. We have been going through massive changes in DiffEqSensitivity and will get the docs up to date very shortly, I have a WIP PR for it https://github.com/JuliaDiffEq/DiffEqDocs.jl/pull/311. Thanks for the effort!

**Comment by Beramos** [comment]
Don't worry I was reading it and saw some mistakes it was only 2min work fixing

**Pull request closed without merging**
