### PR TITLE
Update ensemble.md

### PR DESCRIPTION
**Pull request by logankilpatrick**
Added note about having the correct Julia version.

### CODE REVIEW

**Comment by logankilpatrick** [comment]
Will close #272

**Comment by ChrisRackauckas** [comment]
I think it's assumed no one is on 1.0 anymore. There is a lot more that requires that

**Comment by logankilpatrick** [comment]
Guess I'm in the minority running 1.0.3/1.0.4 :) 

On the contrary, it's the "Long Term Supported Release"

**Comment by ChrisRackauckas** [comment]
I think we'll just punt on this and hope that the long term stable release is soon something that is like 1.4, otherwise we'd need to write this on half of our docs 🤷‍♂ .

**Pull request closed without merging**
