### PR TITLE
Add canonical tags

### LINKED ISSUE #305: Add canonical links to stable for all previously deployed docs
https://github.com/JuliaDiffEq/DiffEqDocs.jl/pull/304#issuecomment-557472754

@fredrikekre suggests @mortenpi has an answer. Would make the search engines prefer replacing all older version doc links with the newer versions.

### PR DESCRIPTION
**Pull request by kanav99**
Fixes #305

### CODE REVIEW

**Comment by kanav99** [comment]
Even GitHub fails to give a nice diff :(

**Comment by ChrisRackauckas** [comment]
Is there a reason this is kept as a draft?

**Comment by kanav99** [comment]
Just so that we don't merge it soon, I don't want it to break until I am convinced that it doesn't break the HTML anywhere.

**Comment by kanav99** [comment]
And it doesn't break anything. Good to go

**Comment by kanav99** [comment]
For references, I wrote this BeautifulSoup script:

```python
from bs4 import BeautifulSoup, Tag
import os

canonical = "https://docs.juliadiffeq.org/stable/"
base = "v6.6.0/"

for subdir, dirs, files in os.walk(base):
    for filename in files:
        filepath = subdir + os.sep + filename

        if filepath.endswith(".html") or filepath.endswith(".htm"):
            f = open(filepath, "r")
            html_data = f.read()
            f.close()
            soup = BeautifulSoup(html_data, 'html.parser')

            if soup.head == None:
                continue
            if len(soup.find_all('link', {'rel': 'canonical'})) == 0:
                # no canonical tag found
                print(filepath)
                if filename == "index.html": # pretty urls is on for this
                    url = filepath[len(base):]
                else: # no pretty urls
                    if filepath.endswith(".htm"):
                        url = filepath[len(base):-4] + "/index.html"
                    elif filepath.endswith(".html"):
                        url = filepath[len(base):-5] + "/index.html"

                if os.path.isfile("v6.8.0/" + url):
                    new_tag = soup.new_tag('link', rel='canonical', href=canonical + url)
                else:
                    new_tag = Tag(builder=soup.builder, name='meta', attrs={'name':'robots','content':'noindex'})
                soup.head.append(new_tag)
                f = open(filepath, "w")
                f.write(str(soup))
                f.close()

```

**Pull request merged**
